import "./globals.css";
import '@fortawesome/fontawesome-free/css/all.min.css';
import 'bootstrap/dist/css/bootstrap.min.css';
import { Onest } from 'next/font/google';
import { Providers } from "@/app/providers";
import UserHeader from "@/common/UserHeader";
import UserSideBar from "@/common/UserSidebar";

const onest = Onest({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  display: 'swap',
});

export const metadata = {
  title: "Nangal-By-Cycle",
  description: "Generated by create next app",
};

export default function UserLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <UserHeader />
          <div className="container" id="main">
            <div className="row">
              <div className="col-md-3 volunteer-contact-form mt-3 rounded-3 p-3" id="sidebar" role="navigation">
                <UserSideBar />
              </div>
              <div className="col-md-9 main mt-3">
                {children}
              </div>
            </div>
          </div>
        </Providers>
      </body>
    </html >
  );
}
