import "./globals.css";
import '@fortawesome/fontawesome-free/css/all.min.css';
import 'bootstrap/dist/css/bootstrap.min.css';
import { Onest } from 'next/font/google';
import 'animate.css/animate.min.css';

const onest = Onest({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  display: 'swap',
});

export const metadata = {
  title: "Nangal-By-Cycle",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={onest.className}>
          {children}
      </body>
    </html>
  );
}
