/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<vovill_id> }
 */
exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex("villages").del();
  await knex("villages").insert([
    { vill_id: 1, village_name: "Ajauli" },
    { vill_id: 2, village_name: "Algran" },
    { vill_id: 3, village_name: "Bainspur" },
    { vill_id: 4, village_name: "Basdehra Brahmna" },
    { vill_id: 5, village_name: "Basdehra Kandla" },
    { vill_id: 6, village_name: "Basdehra Khas" },
    { vill_id: 7, village_name: "Basdehra Rajputan" },
    { vill_id: 8, village_name: "Binnewal" },
    { vill_id: 9, village_name: "Ban Garh" },
    { vill_id: 10, village_name: "Bandleri" },
    { vill_id: 11, village_name: "Barahmpur" },
    { vill_id: 12, village_name: "Bela Dhiani" },
    { vill_id: 13, village_name: "Bela Ramgarh" },
    { vill_id: 14, village_name: "Bhabhaur Sahib" },
    { vill_id: 15, village_name: "Bhalari" },
    { vill_id: 16, village_name: "Bhatoli" },
    { vill_id: 17, village_name: "Bhallan" },
    { vill_id: 18, village_name: "Bhalowal" },
    { vill_id: 19, village_name: "Bhanam" },
    { vill_id: 20, village_name: "Bhangal" },
    { vill_id: 21, village_name: "Bahdala" },
    { vill_id: 22, village_name: "Bhanupal" },
    { vill_id: 23, village_name: "Bhaton" },
    { vill_id: 24, village_name: "Bhikhapur" },
    { vill_id: 25, village_name: "Chhotewal" },
    { vill_id: 26, village_name: "Chabba Nagar" },
    { vill_id: 27, village_name: "Chaukhyal" },
    { vill_id: 28, village_name: "Charatgarh Upperla" },
    { vill_id: 29, village_name: "Chhatarpur" },
    { vill_id: 30, village_name: "Chhatarpur Dhada" },
    { vill_id: 31, village_name: "Dab Khera" },
    { vill_id: 32, village_name: "Daghaur" },
    { vill_id: 33, village_name: "Darauli" },
    { vill_id: 34, village_name: "Diyapur" },
    { vill_id: 35, village_name: "Dohkli" },
    { vill_id: 36, village_name: "Dubheta" },
    { vill_id: 37, village_name: "Duhnal" },
    { vill_id: 38, village_name: "Fatehpur" },
    { vill_id: 39, village_name: "Fatehwal" },
    { vill_id: 40, village_name: "Gohlani" },
    { vill_id: 41, village_name: "Hambewal" },
    { vill_id: 42, village_name: "Harsabela" },
    { vill_id: 43, village_name: "Hazipur" },
    { vill_id: 44, village_name: "Jandla" },
    { vill_id: 45, village_name: "Jindbari" },
    { vill_id: 46, village_name: "Jol" },
    { vill_id: 47, village_name: "Jhorowal" },
    { vill_id: 48, village_name: "Jakhera" },
    { vill_id: 49, village_name: "Jatpur" },
    { vill_id: 50, village_name: "Jatpur Swan" },
    { vill_id: 51, village_name: "Kalitran" },
    { vill_id: 52, village_name: "Kalsera" },
    { vill_id: 53, village_name: "Khera Bagh" },
    { vill_id: 54, village_name: "Kulgraon" },
    { vill_id: 55, village_name: "Khanpur" },
    { vill_id: 56, village_name: "Lamlehra" },
    { vill_id: 57, village_name: "Majari" },
    { vill_id: 58, village_name: "Majara" },
    { vill_id: 59, village_name: "Malukpur" },
    { vill_id: 60, village_name: "Mehal Arian" },
    { vill_id: 61, village_name: "Manakpur" },
    { vill_id: 62, village_name: "Maujowal" },
    { vill_id: 63, village_name: "Medha Majra" },
    { vill_id: 64, village_name: "Meghpur" },
    { vill_id: 65, village_name: "Mehandpur" },
    { vill_id: 66, village_name: "Melwan" },
    { vill_id: 67, village_name: "Mehatpur" },
    { vill_id: 68, village_name: "Mahal Badehar Upnam Dehlan" },
    { vill_id: 69, village_name: "Mahal Bans Bonsre" },
    { vill_id: 70, village_name: "Mahal Mahantan" },
    { vill_id: 71, village_name: "Mahal Nichla Badehar" },
    { vill_id: 72, village_name: "Mahal Uperli Dehlan" },
    { vill_id: 73, village_name: "Mahal Upperla Badehar" },
    { vill_id: 74, village_name: "Nangal Nikku" },
    { vill_id: 75, village_name: "Nangli" },
    { vill_id: 76, village_name: "Nangran Kalmot" },
    { vill_id: 77, village_name: "Nangran Upperla" },
    { vill_id: 78, village_name: "Oustee Colony Block A" },
    { vill_id: 79, village_name: "Oustee Colony Block B" },
    { vill_id: 80, village_name: "Palasi" },
    { vill_id: 81, village_name: "Palsari Raipur" },
    { vill_id: 82, village_name: "Pasiwal" },
    { vill_id: 83, village_name: "Puna" },
    { vill_id: 84, village_name: "Patti" },
    { vill_id: 85, village_name: "Raipur" },
    { vill_id: 86, village_name: "Raipur Nichla" },
    { vill_id: 87, village_name: "Raipur Upperla" },
    { vill_id: 88, village_name: "Rampur Sahni" },
    { vill_id: 89, village_name: "Sainsowal" },
    { vill_id: 90, village_name: "Sangatpur" },
    { vill_id: 91, village_name: "Sehjowal" },
    { vill_id: 92, village_name: "Sukhsal" },
    { vill_id: 93, village_name: "Sanoli" },
    { vill_id: 94, village_name: "Santoshgarh City" },
    { vill_id: 95, village_name: "Santoshgarh Swan" },
    { vill_id: 96, village_name: "Sasan" },
    { vill_id: 97, village_name: "Surewal" },
    { vill_id: 98, village_name: "Swamipur" },
    { vill_id: 99, village_name: "Talwara" },
    { vill_id: 100, village_name: "Takhatpur" },
    { vill_id: 101, village_name: "Thalon" },
    { vill_id: 102, village_name: "Udaypur" },
  ]);
};
