// No "use client" needed
import "./globals.css";
import Header from "../../common/Header";
import Footer from "../../common/Footer";
import '@fortawesome/fontawesome-free/css/all.min.css';
import 'bootstrap/dist/css/bootstrap.min.css';
import CustomCursor from '../../common/CustomCursor';
import { Onest } from 'next/font/google';
import 'animate.css/animate.min.css';
import Wow from "@/common/Wow";
import { Providers } from "../providers";
import { Toaster } from "react-hot-toast";
import FeedbackPopUp from "@/common/FeedBackPopUp";
import "@fancyapps/ui/dist/fancybox/fancybox.css";

const onest = Onest({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  display: 'swap',
});

export const metadata = {
  title: "Nangal-By-Cycle",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={onest.className}>
        <Wow />
        <CustomCursor />
        <Providers>
          <Header />
          {children}
          <Toaster position="top-right" reverseOrder={false} />
        </Providers>
        <Footer />
        <FeedbackPopUp />
      </body>
    </html>
  );
}
